# This Containerfile builds the image that we use in all github workflows.
# When this file is changed, or one needs to rebuild the image for another
# reason, bump the `IMAGE_TAG` in the container.yml workflow.

FROM fedora:41

RUN dnf upgrade -y

# Install dependencies
RUN dnf install -y --setopt=install_weak_deps=False \
    gcc clang \
    ca-certificates \
    desktop-file-utils \
    fuse3 \
    gettext \
    git \
    gnome-desktop-testing \
    gtk-doc \
    jq \
    libcap \
    flatpak-devel \
    fontconfig-devel \
    fuse3-devel \
    gdk-pixbuf2-devel \
    librsvg2 \
    rsvg-pixbuf-loader \
    gstreamer1-plugins-base \
    gstreamer1-plugins-base-devel \
    gstreamer1-plugins-good \
    gst-devtools \
    geoclue2-devel \
    glib2-devel \
    libgudev-devel \
    json-glib-devel \
    pipewire-devel \
    systemd-devel \
    libtool \
    llvm \
    libasan \
    compiler-rt \
    python3-gobject \
    shared-mime-info

# Install meson
RUN dnf install -y --setopt=install_weak_deps=False meson

# Install pytest
RUN dnf install -y --setopt=install_weak_deps=False \
    python3-pytest \
    python3-pytest-xdist \
    python3-dbusmock \
    python3-dbus \
    umockdev \
    umockdev-devel

# Install pip
RUN dnf install -y --setopt=install_weak_deps=False python3-pip

# Install doc dependencies
RUN pip install --user --break-system-packages furo">=2024.04.27" \
    sphinx-copybutton sphinxext-opengraph matplotlib

# Install pre-commit
RUN pip install --user --break-system-packages pre-commit

# Install qdbusxml2cpp
RUN dnf install -y --setopt=install_weak_deps=False qt6-qtbase-devel
